### ISSUE TITLE
GeoPoint takes the current location, even though marker was dropped elsewhere

### ISSUE THREAD

**Issue by zestyping** [getodk/collect#2805]
#### Software and hardware versions 
Collect v1.18.0

#### Problem description
When entering a GeoPoint, if the marker is placed by the initial GPS fix or placed by the user tapping the "add marker" button, the marker on the map does not reflect what is saved; the user's current location at the time they tap the "save" button is recorded as the point, instead.

#### Steps to reproduce the problem (case 1, initial GPS fix)
1. Open a form that has a GeoPoint question with "placement-map" appearance.
 ![screenshot_2019-01-17-10-59-55](https://user-images.githubusercontent.com/236086/51312374-ffc58380-19ff-11e9-94df-8b53f66a9983.png)

2. Launch the map and wait for a GPS fix.  The location icon (green flechette) and point marker (black balloon) appear in the same place. 
![screenshot_2019-01-17-11-00-19](https://user-images.githubusercontent.com/236086/51312376-02c07400-1a00-11e9-8f8c-b189af1dce3d.png)

3. Walk some distance away from the marker.
![screenshot_2019-01-17-11-00-57](https://user-images.githubusercontent.com/236086/51312384-0653fb00-1a00-11e9-929d-dc5b00e3e21d.png)

4. Tap the "save" button (floppy disk icon).  The activity closes, taking us back to the question.
 ![screenshot_2019-01-17-11-01-08](https://user-images.githubusercontent.com/236086/51312390-0a801880-1a00-11e9-9ab2-b14d74e93595.png)

5. Launch the map again.  Notice that the marker has jumped—the recorded coordinates are those of the last location where you were standing, not of the marker that was placed on the map.  (Google Maps will also confirm that the numeric coordinates shown in step 4 also correspond to the last location.)
![screenshot_2019-01-17-11-01-27](https://user-images.githubusercontent.com/236086/51312403-0fdd6300-1a00-11e9-8715-f55010b3a537.png)

#### Steps to reproduce the problem (case 2, dropped marker)
6. While the map is open, tap the "trash" button to clear the marker.  The marker disappears, leaving the green flechette.
![screenshot_2019-01-17-11-01-42](https://user-images.githubusercontent.com/236086/51312406-14098080-1a00-11e9-8bdd-2b8c98d72b1e.png)

7. Walk to a new location.
![screenshot_2019-01-17-11-02-17](https://user-images.githubusercontent.com/236086/51312419-17047100-1a00-11e9-80ef-0d6e65a969ef.png)

8. Tap the "add marker" button (balloon with plus) to drop a marker at your current location.
![screenshot_2019-01-17-11-02-23](https://user-images.githubusercontent.com/236086/51312429-1a97f800-1a00-11e9-81ac-ca33d1589aab.png)

9. Walk some distance away from the marker.
![screenshot_2019-01-17-11-03-15](https://user-images.githubusercontent.com/236086/51312438-1e2b7f00-1a00-11e9-8045-91f3a4d583ea.png)

10. Tap the "save" button (floppy disk icon).  The activity closes, taking us back to the question.
![screenshot_2019-01-17-11-03-22](https://user-images.githubusercontent.com/236086/51312442-21266f80-1a00-11e9-86cc-63c415d46fad.png)

11. Launch the map again and observe that the marker has jumped from the place where you dropped it to the location where you were standing in step 10.
![screenshot_2019-01-17-11-03-28](https://user-images.githubusercontent.com/236086/51312445-2388c980-1a00-11e9-8133-d146e25d514e.png)

#### Expected behavior
The marker should always represent the point that will be recorded when you tap "save".

#### Other information 
To me, this seems like it has to be a bug—it makes no sense that your data should look any different when you save it vs. when you then view what you saved, for any kind of data in any activity.

Oddly, however, this behaviour is quite deliberately coded into the activity; there are flags that keep track of how the marker was placed, and the method that returns the result uses the flags to decide whether to return the marker position or the current GPS location.

So, on the one hand, this seems like clearly a problem to be fixed, and quite a serious one as it invisibly introduces errors in the collected data; and on the other hand, _something_ motivated the original author to code it this way, and perhaps there is a remote possibility that a few users expect it to work this way.  It also seems plausible that no users have reported this problem because they usually tap "save" immediately after dropping the marker.

**Comment by yanokwa** [comment]
This does feel like a bug to me. Geopoint without `placement-map` grabs the current location and so maybe the idea was to keep that behavior consistent.

This code was pulled in from GeoODK and so that behavior might have been useful there? Does `git blame` provide any insight? Either way, I think we should fix it.

**Comment by zestyping** [comment]
@yanokwa Okay.  Yeah, I'd like to fix this.  I'm assuming you mean after 1.19, right?

If you meant to squeeze it into 1.19, I'm happy to do it and think it will be pretty easy from a code perspective; probably of greater concern is the time to do a code review and another round of QA.

**Comment by yanokwa** [comment]
Sorry about the delay, @zestyping. Let's wait to get the standing geo PRs merged, then we can take this on for the next release.

**Comment by yanokwa** [comment]
@zestyping I think this issue was fixed in https://github.com/opendatakit/collect/pull/2865. Can you confirm?

**Comment by zestyping** [comment]
This was not fixed as part of #2865.  There's a bunch of messy logic in there that isn't needed anymore if we no longer want this behaviour, so I'd like to clean that up.  PR coming soon.

**Comment by lognaturel** [comment]
I talked to @zestyping who gave a great reason for why this should be bumped to later. I can't exactly remember what it is, though! I think it's that if we're considering changing the way [points are entered to dragging the map rather than tapping it](https://forum.opendatakit.org/t/placing-geopoints-by-dragging-the-map-instead-of-long-pressing/18389), this issue will go away.

**Comment by zestyping** [comment]
Yes, that's exactly right.  I think we have a consensus that the method described [in this comment](https://forum.opendatakit.org/t/placing-geopoints-by-dragging-the-map-instead-of-long-pressing/18389/14?u=zestyping) for placing point would be easier to use and more precise, and implementing that method would obsolete this issue.  (We should prioritize when we want to go ahead with that work.)

**Comment by lognaturel** [comment]
@seadowg I believe this was fixed in https://github.com/getodk/collect/pull/7253. The PR says no change to behavior but I believe that's where the change was made.

(Hi @zestyping, hope you're well!)
