### ISSUE TITLE
It is possible to edit forms that use entities during form update

### ISSUE THREAD

**Issue by WKobus** [getodk/collect#6715]
#### ODK Collect version
master version cb92cab2a2d5a1150e7c29b10676b12fa425a101
#### Android version
10, 15
#### Device used
Redmi 7, Pixel 6a
#### Problem description
It is possible to edit forms that use entities during form update
#### Steps to reproduce the problem
1. Scan user "edity" from https://test.getodk.cloud/projects/513/app-users
2. Go to trees registration editable form and send it 
3. On central in form access add some other forms to user "edity"
4. Go to start new form and refresh list of forms
5. Quickly go to sent, open previously sent form and press pencil icon
#### Expected behavior
Editing forms that use entities should be blocked during form update

**Comment by seadowg** [comment]
@WKobus I think I misinterpreted the original comment around this. In **5**, when you say "open edit" do you mean that you open to view and hit the ✏️? Either way, please clarify in the steps.

**Comment by WKobus** [comment]
Yea, I meant to press the pencil button. I updated steps to reproduce.

**Comment by seadowg** [comment]
@grzesiek2010 I would have thought this would be blocked, but I can't remember how it worked. Is this potentially fixed by changes in https://github.com/getodk/collect/pull/6709 that remove the new intent type?

**Comment by WKobus** [comment]
Issue still occurs on master version 791154cd7b3b483be01e566ac44a4f47c9efc80e

**Comment by grzesiek2010** [comment]
I'm on it.
